Repository VIAcode/AICore, pull requests merged in 2025-05, with the labels that each got.

#74 SMTP + IMAP + Graph API for Mail + bugfix for WebCrawler and deflate
  AiCoreApi/AiCoreApi.csproj
  AiCoreApi/Common/EntraTokenProvider.cs
  AiCoreApi/Common/Extensions/Extensions.cs
  AiCoreApi/Common/Extensions/HttpExtensions.cs
  AiCoreApi/Models/DbModels/AgentModel.cs
  AiCoreApi/Models/DbModels/ConnectionModel.cs
  AiCoreApi/Models/ViewModels/AgentViewModel.cs
  AiCoreApi/Models/ViewModels/ConnectionViewModel.cs
  AiCoreApi/SemanticKernel/Agents/SmtpNotificationAgent.cs
  AiCoreApi/SemanticKernel/Agents/WebCrawlerAgent.cs
  AiCoreApi/SemanticKernel/PlannerHelpers.cs
  AiCoreApi/Services/ProcessingServices/AgentsHandlers/GraphMailListenerAgentService.cs
  AiCoreApi/Services/ProcessingServices/AgentsHandlers/ImapListenerAgentService.cs
  AiCoreApi/Services/ProcessingServices/BackgroundWorkingHostedService.cs
Labels: enhancement

#75 WebCrawler fix
  AiCoreApi/SemanticKernel/Agents/WebCrawlerAgent.cs
Labels: bug

#76 + Graph Teams Agents
  AiCoreApi/Models/DbModels/AgentModel.cs
  AiCoreApi/Models/ViewModels/AgentViewModel.cs
  AiCoreApi/SemanticKernel/Agents/GraphTeamsNotificationAgent.cs
  AiCoreApi/SemanticKernel/PlannerHelpers.cs
  AiCoreApi/Services/ProcessingServices/AgentsHandlers/AzureServiceBusListenerAgentService.cs
  AiCoreApi/Services/ProcessingServices/AgentsHandlers/GraphMailListenerAgentService.cs
  AiCoreApi/Services/ProcessingServices/AgentsHandlers/GraphTeamsListenerAgentService.cs
  AiCoreApi/Services/ProcessingServices/AgentsHandlers/ImapListenerAgentService.cs
  AiCoreApi/Services/ProcessingServices/AgentsHandlers/RabbitMqListenerAgentService.cs
  AiCoreApi/Services/ProcessingServices/AgentsHandlers/SchedulerAgentService.cs
  AiCoreApi/Services/ProcessingServices/BackgroundWorkingHostedService.cs
Labels: enhancement

#77 Minor fix for GraphTeamsNotificationAgent
  AiCoreApi/SemanticKernel/Agents/GraphTeamsNotificationAgent.cs
Labels: bug

#70 #54270: Monitoring and Metrics: Support OpenTelemetry
  AiCoreApi/AiCoreApi.csproj
  AiCoreApi/Common/ExtendedConfig.cs
  AiCoreApi/Common/Monitoring/CommonMetricsService.cs
  AiCoreApi/Common/Monitoring/MetricsAccessor.cs
  AiCoreApi/Common/Monitoring/MonitoringConfig.cs
  AiCoreApi/Common/Monitoring/ServiceCollectionExtensions.cs
  AiCoreApi/Common/OpenAiHttpCallHandler.cs
  AiCoreApi/Common/RequestAccessor.cs
  AiCoreApi/Controllers/MonitoringSettingsController.cs
  AiCoreApi/Models/DbModels/SettingsModel.cs
  AiCoreApi/Models/ViewModels/LogLevelSettingsViewModel.cs
  AiCoreApi/Models/ViewModels/MonitoringSettingsViewModel.cs
  AiCoreApi/SemanticKernel/Agents/ApiCallAgent.cs
  AiCoreApi/SemanticKernel/Agents/AudioPromptAgent.cs
  AiCoreApi/SemanticKernel/Agents/AzureAiSearchAgent.cs
  AiCoreApi/SemanticKernel/Agents/AzureAiSpeechCreateSpeechAgent.cs
  AiCoreApi/SemanticKernel/Agents/AzureAiTranslatorAgent.cs
  AiCoreApi/SemanticKernel/Agents/AzureLogAnalyticsAgent.cs
  AiCoreApi/SemanticKernel/Agents/AzureServiceBusNotificationAgent.cs
  AiCoreApi/SemanticKernel/Agents/BackgroundWorkerAgent.cs
  AiCoreApi/SemanticKernel/Agents/BaseAgent.cs
  AiCoreApi/SemanticKernel/Agents/BingSearchAgent.cs
  AiCoreApi/SemanticKernel/Agents/CompositeAgent.cs
  AiCoreApi/SemanticKernel/Agents/ContainsAgent.cs
  AiCoreApi/SemanticKernel/Agents/ContentSafetyAgent.cs
  AiCoreApi/SemanticKernel/Agents/CsharpCodeAgent.cs
  AiCoreApi/SemanticKernel/Agents/GoogleSearchApiAgent.cs
  AiCoreApi/SemanticKernel/Agents/HistoryAgent.cs
  AiCoreApi/SemanticKernel/Agents/ImageToTextAgent.cs
  AiCoreApi/SemanticKernel/Agents/JsonTransformAgent.cs
  AiCoreApi/SemanticKernel/Agents/OcrAgent.cs
  AiCoreApi/SemanticKernel/Agents/OcrBuildClassifierAgent.cs
  AiCoreApi/SemanticKernel/Agents/OcrClassifyDocumentAgent.cs
  AiCoreApi/SemanticKernel/Agents/PostgreSqlAgent.cs
  AiCoreApi/SemanticKernel/Agents/PromptAgent.cs
  AiCoreApi/SemanticKernel/Agents/PythonCodeAgent.cs
  AiCoreApi/SemanticKernel/Agents/RabbitMqNotificationAgent.cs
  AiCoreApi/SemanticKernel/Agents/RagPromptAgent.cs
  AiCoreApi/SemanticKernel/Agents/RedisAgent.cs
  AiCoreApi/SemanticKernel/Agents/SmtpNotificationAgent.cs
  AiCoreApi/SemanticKernel/Agents/SqlServerAgent.cs
  AiCoreApi/SemanticKernel/Agents/StabilityAiImagesAgent.cs
  AiCoreApi/SemanticKernel/Agents/StorageAccountAgent.cs
  AiCoreApi/SemanticKernel/Agents/VectorSearchAgent.cs
  AiCoreApi/SemanticKernel/Agents/WebCrawlerAgent.cs
  AiCoreApi/SemanticKernel/Agents/WhisperAgent.cs
  AiCoreApi/SemanticKernel/PlannerHelpers.cs
  AiCoreApi/Services/ControllersServices/ConnectService.cs
  AiCoreApi/Services/ControllersServices/MonitoringSettingsService.cs
  AiCoreApi/Services/ProcessingServices/AgentsHandlers/AgentServiceBase.cs
  AiCoreApi/Startup.cs
  README.md
  docs/Maintenance/Deployment with Docker.md
  docs/Maintenance/Deployment with Helm.md
  docs/Maintenance/Tracing and Metrics.md
Labels: documentation, enhancement

#78 Fix CI errors after merge
  AiCoreApi/SemanticKernel/Agents/GraphTeamsNotificationAgent.cs
Labels: bug

#79 Wrap mail body into Base 64 to prevent conversion issues
  AiCoreApi/Services/ProcessingServices/AgentsHandlers/GraphMailListenerAgentService.cs
  AiCoreApi/Services/ProcessingServices/AgentsHandlers/ImapListenerAgentService.cs
Labels: bug

#81 build fix
  AiCoreApi/Dockerfile
  Dockerfile
Labels: bug
